name: Validate PR Labels

env:
  dart_version: 2.19.2
  flutter_version: 3.7.3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  label_validation:
    name: Validate PR Labels
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          # This ref is required for the GH cli to be able to find which branch it is on
          #   otherwise the checkout pulls code in a detached head state
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: false
          token: '${{ secrets.GH_ACTIONS_PAT }}'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true

      - name: Git Config Update
        run: git config --global url."https://x-token-auth:${{ secrets.GH_ACTIONS_PAT }}@github.com".InsteadOf https://github.com

      - name: Authorize Cloudsmith
        run:  ./shell_scripts/authorize_cloudsmith.sh ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Pub get
        run: flutter pub get

      - name: Validate PR Labels
        run: dart run bin/mplat.dart validate-labels
